[list]
restart = true
enabled = true
send_message = false
processes = ["laradock-portainer-1", "laradock-mysql-1", "laradock-nginx-1", "laradock-php-fpm-1", "laradock-workspace-1", "laradock-phpmyadmin-1","laradock-docker-in-docker-1"]